-- ============================================
-- Supabase Database Scripts — README
-- ============================================
--
-- 最後更新 Last Updated: 2026-01-19
--
-- 目的：
-- - 提供 DB schema/RLS/seed 的可重跑流程（本專案尚未上線，可安全重建）
-- - 避免「手動執行順序」造成 drift（以 COMBINED_* 與 npm scripts 為準）
--
-- Canonical 操作手冊（建議先看這份）：
-- - doc/runbook/database-ops.md
--
-- ============================================
-- 目錄結構（Directory Structure）
-- ============================================
--
-- supabase/
-- ├── 01_drop/                      -- 刪除（重建用；危險）
-- │   ├── 01_main.sql
-- │   ├── 02_comments.sql
-- │   ├── 03_reports.sql
-- │   ├── 04_gallery.sql
-- │   ├── 05_reactions.sql
-- │   ├── 06_feature_settings.sql
-- │   ├── 09_landing_sections.sql
-- │   ├── 10_theme.sql
-- │   ├── 11_users.sql
-- │   ├── 12_ai_analysis.sql
-- │   ├── 13_embeddings.sql
-- │   ├── 15_ai_analysis_templates.sql
-- │   ├── 16_page_views.sql
-- │   ├── 17_ai_analysis_custom_template_refs.sql
-- │   ├── 18_ai_analysis_report_shares.sql
-- │   └── 19_safety_risk_engine.sql
-- │
-- ├── 02_add/                       -- 建立 schema/RLS（主要入口）
-- │   ├── 01_main.sql
-- │   ├── 02_comments.sql
-- │   ├── 03_reports.sql
-- │   ├── 04_gallery.sql
-- │   ├── 05_reactions.sql
-- │   ├── 06_cross_triggers.sql
-- │   ├── 06_feature_settings.sql
-- │   ├── 09_landing_sections.sql
-- │   ├── 10_theme.sql
-- │   ├── 11_users.sql
-- │   ├── 12_ai_analysis.sql
-- │   ├── 13_embeddings.sql
-- │   ├── 14_import_export_jobs.sql
-- │   ├── 15_ai_analysis_templates.sql
-- │   ├── 16_page_views.sql
-- │   ├── 17_ai_analysis_custom_template_refs.sql
-- │   ├── 18_ai_analysis_report_shares.sql
-- │   └── 19_safety_risk_engine.sql
-- │
-- ├── 03_seed/                      -- 預設資料（idempotent 友善）
-- │   ├── 01_main.sql
-- │   ├── 02_comments.sql
-- │   ├── 04_features_landing.sql
-- │   ├── 05_gallery.sql
-- │   ├── 06_blog.sql
-- │   ├── 07_theme.sql
-- │   └── 08_safety.sql
-- │
-- ├── functions/                    -- Supabase Edge Functions（OpenAI embeddings/judge 等）
-- │   └── ...
-- │
-- ├── COMBINED_ADD.sql              -- 一次建立（含 tables/functions/RLS/GRANT）
-- ├── COMBINED_SEED.sql             -- 一次 seed
-- ├── COMBINED_DROP.sql             -- 一次 drop（危險）
-- ├── COMBINED_GRANTS.sql           -- （legacy/rare）僅 grants 的合併檔（通常不需要單獨跑）
-- └── README.sql                    -- 本檔
--
-- ============================================
-- 推薦操作（最少腦力 / 最低 drift）
-- ============================================
--
-- ✅ 推薦：用 npm scripts（會呼叫 scripts/db.mjs；psql 單 transaction）
--
-- 1) 準備環境變數（.env.local；gitignored）
--    SUPABASE_DB_URL=postgresql://postgres:<password>@db.<project-ref>.supabase.co:5432/postgres?sslmode=require
--
-- 2) 指令
--    npm run db:add     -- 建立 schema/RLS/GRANT
--    npm run db:seed    -- 插入 seed data
--    npm run db:drop    -- 刪除所有資料表（危險）
--    npm run db:reset   -- drop → add → seed（本專案尚未上線時最方便）
--
-- ✅ 若你一定要在 Supabase Dashboard → SQL Editor 手動跑：
--    - 重建：COMBINED_DROP.sql → COMBINED_ADD.sql → COMBINED_SEED.sql
--    - 全新：COMBINED_ADD.sql → COMBINED_SEED.sql
--
-- 詳細 SOP / 驗證 SQL / RBAC 設定請看：
-- - doc/runbook/database-ops.md
--
-- ============================================
-- Admin RBAC（必要，否則 RLS 會擋）
-- ============================================
--
-- 本專案的 RLS 主要依賴 JWT 的 app_metadata.role（owner/editor），
-- 不依賴 ADMIN_ALLOWED_EMAILS（那只是 UI gate / fallback）。
--
-- 最小流程：
-- 1) 先讓 Owner/Editor 帳號登入一次（建立 auth.users）
-- 2) 在 SQL Editor 執行：
--
--    insert into public.site_admins (email, role)
--    values ('owner@example.com', 'owner')
--    on conflict (email) do update
--    set role = excluded.role,
--        updated_at = timezone('utc', now());
--
-- 3) 該使用者登出再登入（刷新 JWT claims）
--
-- ============================================
